# set INSTALL_LOC
# set SRC_ROOT
# set ABI
# set PREBUILT
# set CMAKE
# set MAKE
# set PYTHON
# set PERL
# set RUBY
# set BISON
# set GPERF

set -e

mkdir -p ${ABI}/webkit
cd ${ABI}/webkit

$CMAKE -DCMAKE_TOOLCHAIN_FILE=${SRC_ROOT}/android.toolchain.cmake \
-DANDROID_ABI=${ABI} \
-DCMAKE_BUILD_TYPE=MinSizeRel \
-DANDROID_STANDALONE_TOOLCHAIN=${PREBUILT} \
-DANDROID_USE_STLPORT=1 -DENABLE_WEBKIT=0 -ENABLE_WEBCORE=0 -DENABLE_TOOLS=0 \
-DENABLE_WEBKIT=0 -DENABLE_WEBKIT2=0 -DENABLE_API_TESTS=0 -DPORT=Android \
-DCMAKE_FIND_ROOT_PATH=${INSTALL_LOC} \
-DPYTHON_EXECUTABLE=$PYTHON -DPERL_EXECUTABLE=$PERL \
-DRUBY_EXECUTABLE=$RUBY -DENABLE_LLINT=1 -DSHARED_CORE=1 \
-DBISON_EXECUTABLE=$BISON -DGPERF_EXECUTABLE=$GPERF \
-DEXPORT_ONLY_PUBLIC_SYMBOLS=1 -DCMAKE_INSTALL_PREFIX=${INSTALL_LOC}/../../JavaScriptCore \
${SRC_ROOT}/webkit-master/

$MAKE -j8 install

